#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

result=0
for X in */Cargo.toml; do
	DIR="$(dirname "$X")"
	echo :: "$DIR"
	pushd "$DIR" > /dev/null
	"$@" || result=1
	popd > /dev/null
done
exit "$result"
