#!/usr/bin/env bash
for X in */Cargo.toml; do
	DIRNAME="$(dirname "$X")"
	echo ":: $DIRNAME"
	(
		cd "$DIRNAME"
		if grep -q nightly-test Cargo.toml; then
			cargo test --features=nightly-test
		else
			cargo test
		fi
	)
done
