#!/bin/sh
(
echo "#![allow(bad_style)]"
bindgen \
	--no-prepend-enum-name \
	--opaque-type 'GByteArray' \
	--opaque-type 'GHashTable' \
	--opaque-type 'GRegex' \
	--opaque-type 'GSList' \
	--opaque-type 'address' \
	--opaque-type 'epan_column_info' \
	--opaque-type 'epan_session' \
	--opaque-type 'frame_data' \
	--opaque-type 'proto_item' \
	--opaque-type 'proto_tree' \
	--opaque-type 'tvbuff_t' \
	--opaque-type 'wmem_allocator_t' \
	--opaque-type 'wmem_list_t' \
	--opaque-type 'wtap_pkthdr' \
	--opaque-type 'wtap_pseudo_header' \
	--whitelist-function '^add_new_data_source$' \
	--whitelist-function '^col_add_str$' \
	--whitelist-function '^col_clear$' \
	--whitelist-function '^col_set_str$' \
	--whitelist-function '^conversation_set_dissector$' \
	--whitelist-function '^create_dissector_handle$' \
	--whitelist-function '^dissector_add_.*$' \
	--whitelist-function '^find_or_create_conversation$' \
	--whitelist-function '^heur_dissector_add$' \
	--whitelist-function '^proto_item_add_subtree$' \
	--whitelist-function '^proto_item_append_text$' \
	--whitelist-function '^proto_item_set_text$' \
	--whitelist-function '^proto_register_field_array$' \
	--whitelist-function '^proto_register_plugin$' \
	--whitelist-function '^proto_register_protocol$' \
	--whitelist-function '^proto_register_subtree_array$' \
	--whitelist-function '^proto_tree_add_boolean(_format)?$' \
	--whitelist-function '^proto_tree_add_bytes(_format)?$' \
	--whitelist-function '^proto_tree_add_bytes_with_length$' \
	--whitelist-function '^proto_tree_add_float(_format)?$' \
	--whitelist-function '^proto_tree_add_guid(_format)?$' \
	--whitelist-function '^proto_tree_add_int(_format)?$' \
	--whitelist-function '^proto_tree_add_item$' \
	--whitelist-function '^proto_tree_add_none_format?$' \
	--whitelist-function '^proto_tree_add_string(_format)?$' \
	--whitelist-function '^proto_tree_add_uint(_format)?$' \
	--whitelist-function '^tvb_memcpy$' \
	--whitelist-function '^tvb_new_child_real_data$' \
	--whitelist-function '^tvb_new_subset_remaining$' \
	--whitelist-function '^tvb_reported_length$' \
	--whitelist-function '^wmem_alloc$' \
	--whitelist-type '^field_display_e$' \
	--whitelist-var '^COL_INFO$' \
	--whitelist-var '^ENC_BIG_ENDIAN$' \
	--whitelist-var '^ENC_NA$' \
	bindgen.h \
	-- \
	$(pkg-config wireshark --cflags)
echo
) > src/lib.rs
python3 fix.py src/lib.rs
python3 extract_def_file.py src/lib.rs /usr/lib src/ wireshark wsutil
cargo fmt

# These makes the resulting source contain errors.
#--opaque-type 'circuit_type' \
#--opaque-type 'port_type' \
