[package]
name = "gamenet"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]

[dependencies]
arrayvec = "0.3.12"
buffer = "0.1.5"
quickcheck = "0.4.1"
common = { path = "../common/" }
packer = { path = "../packer/" }
warn = ">=0.1.1,<0.3.0"

[dev-dependencies]
hexdump = "0.1.0"
