#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

python3 generate/enums.py > src/enums.rs
python3 generate/msg_connless.py > src/msg/connless.rs
python3 generate/msg_game.py > src/msg/game.rs
python3 generate/msg_system.py > src/msg/system.rs
python3 generate/snap_obj.py > src/snap_obj.rs
