#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

python3 generate/generate.py generate/spec/teeworlds-0.5.json teeworlds-0.5 gamenet_teeworlds_0_5
python3 generate/generate.py generate/spec/teeworlds-0.6.json teeworlds-0.6 gamenet_teeworlds_0_6
python3 generate/generate.py generate/spec/teeworlds-0.7.5.json teeworlds-0.7.5 gamenet_teeworlds_0_7_5
python3 generate/generate.py generate/spec/ddnet-15.2.5.json ddnet-15.2.5 gamenet_ddnet_15_2_5
